### ISSUE TITLE
Organization Management - Filter Pop Up

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#94] opened 2019-04-11 16:20 UTC
![Org Management Filter Pop Up](https://user-images.githubusercontent.com/48923883/55973743-0ba99600-5c3b-11e9-8f18-5662c7225468.png)

**Comment by akhilesh-94** [comment] 2019-04-12 15:45
Duplicate of #23

**Comment by JRWinWin** [comment] 2019-04-12 15:50
Do you need the NTEE/NAICS reference lists?

**Comment by akhilesh-94** [comment] 2019-04-12 15:59
> Do you need the NTEE/NAICS reference lists?

@sunnytambi Could you weigh in on this?

**Comment by akhilesh-94** [comment] 2019-04-15 09:09
> Do you need the NTEE/NAICS reference lists?

Yes, we will be needing the reference lists

**Comment by BethRR** [comment] 2019-06-03 17:44
confirmed fix

**Closed by BethRR** 2019-06-03 17:44 UTC
Labels: duplicate, fixed
