### ISSUE TITLE
Organization Management Cannot Load Full Organization List - CRITICAL

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#329] opened 2019-06-20 21:32 UTC
![Loading Org Management Screen](https://user-images.githubusercontent.com/48923883/59882560-606a3b00-9367-11e9-96d3-a87e25107d78.png)

After logging in to the MVP Console, the Organization Management page never loads completely. It resembles the attached photo.
It can be navigated around by applying a filter, then the subsection of the list is presented.

Expected: The landing, or Organization Management, page of the MVP must work.

**Comment by akhilesh-94** [comment] 2019-06-21 08:27
Duplicate of #330

**Closed** 2019-07-01 18:42 UTC
Labels: Backend, bug, fixed
