### ISSUE TITLE
Org Management Check Box application across similar names

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#429] opened 2019-07-09 23:03 UTC
<img width="1212" alt="Screen Shot 2019-07-09 at 3 56 09 PM" src="https://user-images.githubusercontent.com/48923883/60928524-9e6dc700-a262-11e9-87cd-a90b68ed5b98.png">

<img width="1208" alt="Screen Shot 2019-07-09 at 3 56 19 PM" src="https://user-images.githubusercontent.com/48923883/60928534-a3cb1180-a262-11e9-81de-15e6dc3bb9a2.png">

Issue: In Organization Management, if two or more organizations have the same Name, and one of their check boxes are selected, all of those organizations' checkboxes will get selected automatically. Multiple organizations will have the same name, but will be different entities. A user must be able to select one at a time via checkbox to effectively use this MVP.

**Comment by akhilesh-94** [comment] 2019-07-10 13:49
Duplicate of #424

**Closed** 2019-07-10 14:57 UTC
Labels: bug, fixed
