### ISSUE TITLE
Upload attempt of 133k rows- FAILED

### ISSUE THREAD

**Issue by JRWinWin** [winwinwiki/winwin-frontend#373] opened 2019-07-01 21:26 UTC
Issue: The bulk upload feature is still not functioning properly. I attempted to upload a file with 133k rows and the process was not completed. 
Attached is the error message that is created when the process stops. 
![133k failed rows error message](https://user-images.githubusercontent.com/48923883/60467697-2bce6d00-9c0c-11e9-8d75-7e9b9a7f6066.png)

**Comment by JRWinWin** [comment] 2019-07-01 21:58
An upload attempt of 1k rows was successful.

**Comment by akhilesh-94** [comment] 2019-07-02 10:05
Duplicate of #314

**Comment by JRWinWin** [comment] 2019-07-03 18:50
An upload attempted of 133k (same as original issue) failed today

**Comment by JRWinWin** [comment] 2019-07-03 18:53
![Screen Shot 2019-07-03 at 11 53 38 AM](https://user-images.githubusercontent.com/48923883/60617739-36fad780-9d89-11e9-85dd-ac6a7167eec2.png)
This is the associated error

**Comment by arvindkhatik012** [comment] 2019-07-19 10:10
The 133k organizations are uploaded by john are available in DB so, marking the issue as fixed.

**Closed** 2019-07-19 17:54 UTC
Labels: Pri 1, bug, fixed
